Check duplications in dictionary

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -296,3 +296,13 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - run: npx cspell --no-progress $(git ls-files)
+      - name: Check duplications in dictionary
+        run: |
+          dup=$(sed '/^$/d' .github/.cspell/dictionary.txt | LC_ALL=C sort -f | uniq -d -i)
+          if [[ -n "${dup}" ]]; then
+              echo "error: duplicated words in .github/.cspell/dictionary.txt"
+              echo "======================================="
+              echo "${dup}"
+              echo "======================================="
+              exit 1
+          fi
