wip

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,110 +27,110 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  build:
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-latest, macos-latest, windows-latest]
-    runs-on: ${{ matrix.os }}
-    timeout-minutes: 60
-    steps:
-      - uses: actions/checkout@v4
-      - uses: dtolnay/rust-toolchain@stable
-      - uses: Swatinem/rust-cache@v2
-      - uses: taiki-e/install-action@protoc
-      - run: ci/free-device-space.sh
-      - run: ci/ubuntu-setup-lld.sh
-        if: startsWith(matrix.os, 'ubuntu')
-      - run: ci/ubuntu-install-dependencies.sh
-        if: startsWith(matrix.os, 'ubuntu')
-      - run: cargo build
+  # build:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os: [ubuntu-latest, macos-latest, windows-latest]
+  #   runs-on: ${{ matrix.os }}
+  #   timeout-minutes: 60
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: dtolnay/rust-toolchain@stable
+  #     - uses: Swatinem/rust-cache@v2
+  #     - uses: taiki-e/install-action@protoc
+  #     - run: ci/free-device-space.sh
+  #     - run: ci/ubuntu-setup-lld.sh
+  #       if: startsWith(matrix.os, 'ubuntu')
+  #     - run: ci/ubuntu-install-dependencies.sh
+  #       if: startsWith(matrix.os, 'ubuntu')
+  #     - run: cargo build
 
-  test:
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-latest, macos-latest, windows-latest]
-    runs-on: ${{ matrix.os }}
-    timeout-minutes: 60
-    steps:
-      - uses: actions/checkout@v4
-      - uses: dtolnay/rust-toolchain@stable
-      - uses: Swatinem/rust-cache@v2
-      - uses: taiki-e/install-action@protoc
-      - run: ci/free-device-space.sh
-      - run: ci/ubuntu-setup-lld.sh
-        if: startsWith(matrix.os, 'ubuntu')
-      - run: ci/ubuntu-install-dependencies.sh
-        if: startsWith(matrix.os, 'ubuntu')
-      # testing arci-ros/arci-ros2 is done in ros1_arci_ros, ros1_openrr_apps, and ros2_arci_ros2
-      - run: cargo test --workspace --exclude arci-ros --exclude arci-ros2 --exclude openrr-apps
-      - name: cargo test (openrr-apps without ros)
-        working-directory: openrr-apps
-        run: cargo test --no-default-features --features gui,assimp
+  # test:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os: [ubuntu-latest, macos-latest, windows-latest]
+  #   runs-on: ${{ matrix.os }}
+  #   timeout-minutes: 60
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: dtolnay/rust-toolchain@stable
+  #     - uses: Swatinem/rust-cache@v2
+  #     - uses: taiki-e/install-action@protoc
+  #     - run: ci/free-device-space.sh
+  #     - run: ci/ubuntu-setup-lld.sh
+  #       if: startsWith(matrix.os, 'ubuntu')
+  #     - run: ci/ubuntu-install-dependencies.sh
+  #       if: startsWith(matrix.os, 'ubuntu')
+  #     # testing arci-ros/arci-ros2 is done in ros1_arci_ros, ros1_openrr_apps, and ros2_arci_ros2
+  #     - run: cargo test --workspace --exclude arci-ros --exclude arci-ros2 --exclude openrr-apps
+  #     - name: cargo test (openrr-apps without ros)
+  #       working-directory: openrr-apps
+  #       run: cargo test --no-default-features --features gui,assimp
 
-  ros1_arci_ros:
-    strategy:
-      fail-fast: false
-      matrix:
-        distro:
-          - noetic
-    runs-on: ubuntu-latest
-    timeout-minutes: 60
-    container:
-      image: docker://ros:${{ matrix.distro }}-ros-base
-    env:
-      HOME: /root
-    steps:
-      - uses: actions/checkout@v4
-      - run: |
-          apt-get update
-          apt-get -y install curl libudev-dev
-      - uses: dtolnay/rust-toolchain@stable
-      - uses: Swatinem/rust-cache@v2
-        with:
-          # rust-cache does not recognize the matrix.
-          key: ros1_arci_ros-${{ matrix.distro }}
-      - run: ci/ubuntu-setup-lld.sh
-      - name: cargo everything
-        shell: bash -ieo pipefail {0}
-        working-directory: arci-ros
-        run: |
-          source /opt/ros/${{ matrix.distro }}/setup.bash
-          rosdep install -y -i --from-paths .
-          cargo test
+  # ros1_arci_ros:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       distro:
+  #         - noetic
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 60
+  #   container:
+  #     image: docker://ros:${{ matrix.distro }}-ros-base
+  #   env:
+  #     HOME: /root
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - run: |
+  #         apt-get update
+  #         apt-get -y install curl libudev-dev
+  #     - uses: dtolnay/rust-toolchain@stable
+  #     - uses: Swatinem/rust-cache@v2
+  #       with:
+  #         # rust-cache does not recognize the matrix.
+  #         key: ros1_arci_ros-${{ matrix.distro }}
+  #     - run: ci/ubuntu-setup-lld.sh
+  #     - name: cargo everything
+  #       shell: bash -ieo pipefail {0}
+  #       working-directory: arci-ros
+  #       run: |
+  #         source /opt/ros/${{ matrix.distro }}/setup.bash
+  #         rosdep install -y -i --from-paths .
+  #         cargo test
 
-  ros1_openrr_apps:
-    strategy:
-      fail-fast: false
-      matrix:
-        distro:
-          - noetic
-    runs-on: ubuntu-latest
-    timeout-minutes: 60
-    container:
-      image: docker://ros:${{ matrix.distro }}-ros-base
-    env:
-      HOME: /root
-    steps:
-      - uses: actions/checkout@v4
-      - run: |
-          apt-get update
-          apt-get -y install curl ros-${{ matrix.distro }}-pr2-description
-      - uses: dtolnay/rust-toolchain@stable
-      - uses: Swatinem/rust-cache@v2
-        with:
-          # rust-cache does not recognize the matrix.
-          key: ros1_openrr_apps-${{ matrix.distro }}
-      - run: ci/ubuntu-setup-lld.sh
-      - run: ci/ubuntu-install-dependencies.sh
-      - name: cargo test
-        shell: bash -ieo pipefail {0}
-        working-directory: openrr-apps
-        run: |
-          source /opt/ros/${{ matrix.distro }}/setup.bash
-          rosdep install -y -i --from-paths .
-          cargo test --no-default-features --features ros,assimp
+  # ros1_openrr_apps:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       distro:
+  #         - noetic
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 60
+  #   container:
+  #     image: docker://ros:${{ matrix.distro }}-ros-base
+  #   env:
+  #     HOME: /root
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - run: |
+  #         apt-get update
+  #         apt-get -y install curl ros-${{ matrix.distro }}-pr2-description
+  #     - uses: dtolnay/rust-toolchain@stable
+  #     - uses: Swatinem/rust-cache@v2
+  #       with:
+  #         # rust-cache does not recognize the matrix.
+  #         key: ros1_openrr_apps-${{ matrix.distro }}
+  #     - run: ci/ubuntu-setup-lld.sh
+  #     - run: ci/ubuntu-install-dependencies.sh
+  #     - name: cargo test
+  #       shell: bash -ieo pipefail {0}
+  #       working-directory: openrr-apps
+  #       run: |
+  #         source /opt/ros/${{ matrix.distro }}/setup.bash
+  #         rosdep install -y -i --from-paths .
+  #         cargo test --no-default-features --features ros,assimp
 
   ros2_arci_ros2:
     strategy:
@@ -173,163 +173,163 @@ jobs:
         working-directory: arci-ros2
         run: |
           source /opt/ros/$ROS2_DISTRO/setup.bash
-          cargo test
+          cargo test -- --nocapture
 
-  # When this job failed, run tools/update-schema.sh and commit result changes.
-  schema:
-    runs-on: ubuntu-latest
-    timeout-minutes: 60
-    steps:
-      - uses: actions/checkout@v4
-      - uses: dtolnay/rust-toolchain@stable
-      - uses: Swatinem/rust-cache@v2
-      - run: ci/ubuntu-install-dependencies.sh
-      - run: tools/update-schema.sh
-      - run: git add -N . && git diff --exit-code
+  # # When this job failed, run tools/update-schema.sh and commit result changes.
+  # schema:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 60
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: dtolnay/rust-toolchain@stable
+  #     - uses: Swatinem/rust-cache@v2
+  #     - run: ci/ubuntu-install-dependencies.sh
+  #     - run: tools/update-schema.sh
+  #     - run: git add -N . && git diff --exit-code
 
-  # When this job failed, run tools/gen-code.sh and commit result changes.
-  codegen:
-    runs-on: ubuntu-latest
-    timeout-minutes: 60
-    steps:
-      - uses: actions/checkout@v4
-      - uses: dtolnay/rust-toolchain@stable
-      - uses: Swatinem/rust-cache@v2
-      - uses: taiki-e/install-action@protoc
-      - run: tools/gen-code.sh
-      - run: git add -N . && git diff --exit-code
+  # # When this job failed, run tools/gen-code.sh and commit result changes.
+  # codegen:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 60
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: dtolnay/rust-toolchain@stable
+  #     - uses: Swatinem/rust-cache@v2
+  #     - uses: taiki-e/install-action@protoc
+  #     - run: tools/gen-code.sh
+  #     - run: git add -N . && git diff --exit-code
 
-  # Check all feature combinations work properly.
-  features:
-    name: Check features
-    runs-on: ubuntu-latest
-    timeout-minutes: 60
-    steps:
-      - uses: actions/checkout@v4
-      - uses: dtolnay/rust-toolchain@stable
-      - uses: Swatinem/rust-cache@v2
-      - run: ci/ubuntu-install-dependencies.sh
-      - name: Install cargo-hack
-        uses: taiki-e/install-action@cargo-hack
-      - uses: taiki-e/install-action@protoc
-      - run: cargo hack check --all --feature-powerset --optional-deps
+  # # Check all feature combinations work properly.
+  # features:
+  #   name: Check features
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 60
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: dtolnay/rust-toolchain@stable
+  #     - uses: Swatinem/rust-cache@v2
+  #     - run: ci/ubuntu-install-dependencies.sh
+  #     - name: Install cargo-hack
+  #       uses: taiki-e/install-action@cargo-hack
+  #     - uses: taiki-e/install-action@protoc
+  #     - run: cargo hack check --all --feature-powerset --optional-deps
 
-  fmt:
-    name: Format
-    runs-on: ubuntu-latest
-    timeout-minutes: 60
-    steps:
-      - uses: actions/checkout@v4
-      - uses: dtolnay/rust-toolchain@nightly
-        with:
-          toolchain: ${{ env.nightly }}
-          components: rustfmt
-      - run: cargo fmt --all --check
-      - name: Format YAML
-        run: npx -y prettier -c $(git ls-files '*.yml') || (echo "::warning::Please run \`prettier -l -w \$(git ls-files '*.yml')\` to fix format" && exit 1)
-        if: always()
+  # fmt:
+  #   name: Format
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 60
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: dtolnay/rust-toolchain@nightly
+  #       with:
+  #         toolchain: ${{ env.nightly }}
+  #         components: rustfmt
+  #     - run: cargo fmt --all --check
+  #     - name: Format YAML
+  #       run: npx -y prettier -c $(git ls-files '*.yml') || (echo "::warning::Please run \`prettier -l -w \$(git ls-files '*.yml')\` to fix format" && exit 1)
+  #       if: always()
 
-  clippy:
-    name: Clippy
-    runs-on: ubuntu-22.04
-    timeout-minutes: 60
-    steps:
-      - uses: actions/checkout@v4
-      - uses: dtolnay/rust-toolchain@stable
-        with:
-          components: clippy
-      - uses: Swatinem/rust-cache@v2
-      - uses: taiki-e/install-action@protoc
-      - run: ci/ubuntu-install-dependencies.sh
-      - name: Run clippy
-        run: cargo clippy --all-features --all-targets
+  # clippy:
+  #   name: Clippy
+  #   runs-on: ubuntu-22.04
+  #   timeout-minutes: 60
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: dtolnay/rust-toolchain@stable
+  #       with:
+  #         components: clippy
+  #     - uses: Swatinem/rust-cache@v2
+  #     - uses: taiki-e/install-action@protoc
+  #     - run: ci/ubuntu-install-dependencies.sh
+  #     - name: Run clippy
+  #       run: cargo clippy --all-features --all-targets
 
-  docs:
-    name: Docs
-    runs-on: ubuntu-22.04
-    timeout-minutes: 60
-    steps:
-      - uses: actions/checkout@v4
-      - uses: dtolnay/rust-toolchain@stable
-      - uses: Swatinem/rust-cache@v2
-      - uses: taiki-e/install-action@protoc
-      - run: ci/ubuntu-install-dependencies.sh
-      - run: cargo doc --workspace --all-features
-      - name: Publish documentation
-        run: |
-          cd target/doc
-          git init
-          git add .
-          git -c user.name='ci' -c user.email='ci' commit -m 'Deploy OpenRR API documentation'
-          git push -f -q https://git:${{ secrets.github_token }}@github.com/${{ github.repository }} HEAD:gh-pages
-        if: github.event_name == 'push' && github.event.ref == 'refs/heads/main' && github.repository_owner == 'openrr'
+  # docs:
+  #   name: Docs
+  #   runs-on: ubuntu-22.04
+  #   timeout-minutes: 60
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: dtolnay/rust-toolchain@stable
+  #     - uses: Swatinem/rust-cache@v2
+  #     - uses: taiki-e/install-action@protoc
+  #     - run: ci/ubuntu-install-dependencies.sh
+  #     - run: cargo doc --workspace --all-features
+  #     - name: Publish documentation
+  #       run: |
+  #         cd target/doc
+  #         git init
+  #         git add .
+  #         git -c user.name='ci' -c user.email='ci' commit -m 'Deploy OpenRR API documentation'
+  #         git push -f -q https://git:${{ secrets.github_token }}@github.com/${{ github.repository }} HEAD:gh-pages
+  #       if: github.event_name == 'push' && github.event.ref == 'refs/heads/main' && github.repository_owner == 'openrr'
 
-  deny:
-    runs-on: ubuntu-latest
-    timeout-minutes: 60
-    steps:
-      - uses: actions/checkout@v4
-      - uses: dtolnay/rust-toolchain@stable
-      - uses: taiki-e/install-action@cargo-deny
-      # Workaround for https://github.com/EmbarkStudios/cargo-deny/issues/413
-      - uses: taiki-e/install-action@cargo-no-dev-deps
-      - run: cargo no-dev-deps deny --workspace --all-features check
+  # deny:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 60
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: dtolnay/rust-toolchain@stable
+  #     - uses: taiki-e/install-action@cargo-deny
+  #     # Workaround for https://github.com/EmbarkStudios/cargo-deny/issues/413
+  #     - uses: taiki-e/install-action@cargo-no-dev-deps
+  #     - run: cargo no-dev-deps deny --workspace --all-features check
 
-  shellcheck:
-    runs-on: ubuntu-latest
-    timeout-minutes: 60
-    steps:
-      - uses: actions/checkout@v4
-      - name: Install latest shellcheck
-        uses: taiki-e/install-action@shellcheck
-      - run: shellcheck $(git ls-files '*.sh')
+  # shellcheck:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 60
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - name: Install latest shellcheck
+  #       uses: taiki-e/install-action@shellcheck
+  #     - run: shellcheck $(git ls-files '*.sh')
 
-  markdownlint:
-    runs-on: ubuntu-latest
-    timeout-minutes: 60
-    steps:
-      - uses: actions/checkout@v4
-      - run: npx -y markdownlint-cli2 $(git ls-files '*.md')
+  # markdownlint:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 60
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - run: npx -y markdownlint-cli2 $(git ls-files '*.md')
 
-  spell-check:
-    runs-on: ubuntu-latest
-    timeout-minutes: 60
-    steps:
-      - uses: actions/checkout@v4
-      - run: tools/spell-check.sh
+  # spell-check:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 60
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - run: tools/spell-check.sh
 
-  coverage:
-    runs-on: ubuntu-20.04
-    timeout-minutes: 120
-    steps:
-      - uses: actions/checkout@v4
-      - uses: taiki-e/install-action@protoc
-      - run: ci/free-device-space.sh
-      - run: ci/ubuntu-install-dependencies.sh
-      - run: ci/ubuntu-setup-lld.sh
-      - name: Install ROS1
-        run: |
-          # ros1
-          sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
-          sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
+  # coverage:
+  #   runs-on: ubuntu-20.04
+  #   timeout-minutes: 120
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: taiki-e/install-action@protoc
+  #     - run: ci/free-device-space.sh
+  #     - run: ci/ubuntu-install-dependencies.sh
+  #     - run: ci/ubuntu-setup-lld.sh
+  #     - name: Install ROS1
+  #       run: |
+  #         # ros1
+  #         sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
+  #         sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
 
-          sudo apt-get update
-          sudo apt-get install -y \
-            ros-noetic-ros-base ros-noetic-joy ros-noetic-pr2-description
-      - uses: dtolnay/rust-toolchain@stable
-      - uses: Swatinem/rust-cache@v2
-      - name: Install cargo-llvm-cov
-        uses: taiki-e/install-action@cargo-llvm-cov
-      - name: Generate code coverage
-        run: |
-          # for test of arci-ros (roscore, rostopic)
-          source /opt/ros/noetic/setup.bash
-          # --exclude arci-ros2 due to foxy was EoL on 2023-06-20
-          # --no-cfg-coverage due to https://github.com/Smithay/calloop/issues/118
-          cargo llvm-cov --verbose --all-features --workspace --exclude openrr-internal-codegen --exclude arci-ros2 --no-cfg-coverage --codecov --output-path codecov.json
-      - name: Upload to codecov.io
-        uses: codecov/codecov-action@v1
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
-          files: codecov.json
-          fail_ci_if_error: true
+  #         sudo apt-get update
+  #         sudo apt-get install -y \
+  #           ros-noetic-ros-base ros-noetic-joy ros-noetic-pr2-description
+  #     - uses: dtolnay/rust-toolchain@stable
+  #     - uses: Swatinem/rust-cache@v2
+  #     - name: Install cargo-llvm-cov
+  #       uses: taiki-e/install-action@cargo-llvm-cov
+  #     - name: Generate code coverage
+  #       run: |
+  #         # for test of arci-ros (roscore, rostopic)
+  #         source /opt/ros/noetic/setup.bash
+  #         # --exclude arci-ros2 due to foxy was EoL on 2023-06-20
+  #         # --no-cfg-coverage due to https://github.com/Smithay/calloop/issues/118
+  #         cargo llvm-cov --verbose --all-features --workspace --exclude openrr-internal-codegen --exclude arci-ros2 --no-cfg-coverage --codecov --output-path codecov.json
+  #     - name: Upload to codecov.io
+  #       uses: codecov/codecov-action@v1
+  #       with:
+  #         token: ${{ secrets.CODECOV_TOKEN }}
+  #         files: codecov.json
+  #         fail_ci_if_error: true
